import Link from "next/link";
import Logo from "../components/Logo";

export default function TermsOfService() {
  return (
    <div style={{ minHeight: "100vh", background: "#FDFCF8", color: "#18120A", fontFamily: "var(--font-sans)" }}>
      <header style={{ borderBottom: "1px solid rgba(24,18,10,0.06)", background: "#F5F0E8" }}>
        <nav style={{ maxWidth: 800, margin: "0 auto", padding: "1.25rem 2rem", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <Link href="/" style={{ display: "flex", alignItems: "center", gap: "0.5rem", textDecoration: "none" }}>
            <Logo size={28} />
            <span style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: "1.1rem", fontWeight: 600, color: "#18120A" }}>ContractSense</span>
          </Link>
          <Link href="/" style={{ fontSize: "0.85rem", fontWeight: 600, color: "#B8742E", textDecoration: "none" }}>← Back to Home</Link>
        </nav>
      </header>

      <main style={{ maxWidth: 800, margin: "0 auto", padding: "4rem 2rem 6rem" }}>
        <div style={{ marginBottom: "3rem" }}>
          <h1 style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: "2.5rem", fontWeight: 500, letterSpacing: "-0.03em", marginBottom: "0.5rem" }}>Terms of Service</h1>
          <p style={{ color: "rgba(24,18,10,0.5)", fontSize: "0.85rem" }}>Last Updated: August 28, 2026</p>
        </div>

        <div style={{ fontSize: "0.95rem", lineHeight: 1.8, color: "#4A4036", display: "flex", flexDirection: "column", gap: "1.75rem" }}>
          <section>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 700, color: "#18120A", marginBottom: "0.75rem" }}>1. Acceptance of Terms</h2>
            <p>By accessing and using ContractSense ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 700, color: "#18120A", marginBottom: "0.75rem" }}>2. Nature of Service & Disclaimer</h2>
            <p><strong>Not Legal Advice:</strong> ContractSense provides AI-powered contract analysis, statutory risk flagging (including MSMED Act 2006 compliance), and regional translation services. The output generated by the Service is for informational and auditing purposes only. It does not constitute formal legal advice, and no attorney-client relationship is formed. You should always consult a qualified legal professional before executing any legal agreement.</p>
          </section>

          <section>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 700, color: "#18120A", marginBottom: "0.75rem" }}>3. User Responsibilities</h2>
            <p>You agree not to:</p>
            <ul style={{ paddingLeft: "1.25rem", marginTop: "0.5rem", display: "flex", flexDirection: "column", gap: "0.4rem" }}>
              <li>Upload documents containing classified government data, illicit material, or content you do not have the right to process.</li>
              <li>Attempt to reverse-engineer, decompile, or extract the source code of the Service.</li>
              <li>Use the Service to generate advice for third parties without disclosing the automated nature of the analysis.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 700, color: "#18120A", marginBottom: "0.75rem" }}>4. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, ContractSense shall not be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Service or reliance on its analysis.</p>
          </section>

          <section>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 700, color: "#18120A", marginBottom: "0.75rem" }}>5. Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts located in New Delhi, India.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
